
# Base Docker compose for all environments
version: "3.4"

services:
  indexer:
    restart: always
    env_file:
      - .env.duck
      - .env
    volumes:
      - ./services/discord-indexer:/app
      - ./shared:/app/shared
    build: ./services/discord-indexer
  message-generator_0: &message-generator
    restart: always
    env_file:
      - .env.duck
      - .env
    volumes:
      - ./services/discord-message-generator:/app
      - ./shared:/app/shared
      - ./models:/app/models
    build: ./services/discord-message-generator
  message-dispatcher:
    restart: always
    env_file:
      - .env.duck
      - .env
    volumes:
      - ./services/discord-message-dispatcher:/app
      - ./shared:/app/shared
    build: ./services/discord-message-dispatcher
  model-trainer:
    restart: always
    env_file:
      - .env.duck
      - .env
    volumes:
      - ./services/model-trainer:/app
      - ./shared:/app/shared
      - ./models:/app/models
    build: ./services/model-trainer
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "2" ]
              capabilities: [gpu]
