services:
  # message-vector-embedder:
  #   restart: always
  #   depends_on:
  #     - mongo
  #   networks:
  #     - mongo
  #   env_file:
  #     - .env.duck
  #   volumes:
  #     - ./services/hy/message-vector-embedder:/app
  #     - ./hy/shared:/app/shared
  #   build: ./services/hy/gpt-trainer
  indexer:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/hy/discord-indexer:/app
      - ./shared/hy:/app/shared
    build: ./services/hy/discord-indexer
  message-dispatcher:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/hy/discord-message-dispatcher:/app
      - ./shared/hy:/app/shared
    build: ./services/hy/discord-message-dispatcher
  gpt-generator:
    restart: always

    depends_on:
      - mongo

    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/hy/gpt-generator:/app
      - ./shared/hy:/app/shared
      - ./models:/app/models
    build: ./services/hy/gpt-generator
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [gpu]
  gpt-trainer:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/hy/gpt-trainer:/app
      - ./shared/hy:/app/shared
      - ./models:/app/models
    build: ./services/hy/gpt-trainer
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "2" ]
              capabilities: [gpu]
  mongo:
    restart: always
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - mongo
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  # chroma:
  #   restart: always
  #   image: chroma
  #   volumes:
  #     - ./data/chroma:/chroma/chroma
  #   networks:
  #     - chroma
  #   expose:
  #     - 8000
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command:
      redis-server --save 20 1 \
        --loglevel warning \
        --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
networks:
  mongo:
  chroma:
