services:
  gpt-generator:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/gpt-generator:/app
      - ./shared:/app/shared
    build: ./services/gpt-generator
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "2" ]
              capabilities: [gpu]
  mongo:
    restart: always
    image: mongo
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./data:/data/db
    networks:
      - mongo
    expose:
      - 27017
networks:
  react-express:
  mongo:
