services:
  mongo:
    restart: always
    image: mongo
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./data:/data/db
    networks:
      - mongo
    expose:
      - 27017
networks:
  react-express:
  mongo:
