services:
  gpt-generator:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - ../../../.env.duck
    volumes:
      - ./services/gpt-generator:/app
      - ./shared:/app/shared
    build: ./services/gpt-generator
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "2" ]
              capabilities: [gpu]
