version: "3.4"
services:
  gpt-trainer:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - ../../../.env.duck
    volumes:
      - ./services/gpt-trainer:/app
      - ./shared:/app/shared
      - ./nano_gpt_model:/app/models
    build: ./services/gpt-trainer
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "2" ]
              capabilities: [gpu]
